In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3, 4])

In [3]:
a1

array([1, 2, 3, 4])

In [4]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [5]:
np.zeros((4, 5, 6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [6]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
a2.ndim

2

In [9]:
a2.shape

(2, 3)

In [10]:
a2.dtype

dtype('int64')

In [12]:
arr = np.arange(9)

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
arr.reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
arr + 1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])