# numpy

## creating arrays

* ndarray 
* typed <-- all values are same type in that array
  * int32, int64, float64, unicode

In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array((1, 2, 3))

array([1, 2, 3])

In [4]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [5]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
np.zeros((3,))

array([0., 0., 0.])

In [7]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [8]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.random.randn(3, 2)

array([[-2.03595968,  0.76792863],
       [-0.17537817,  0.00306995],
       [ 1.09916961,  2.0728488 ]])

In [10]:
np.random.randint(1, 6, (3,))

array([2, 1, 5])

In [11]:
arr = np.arange(9)

In [13]:
arr.shape

(9,)

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [15]:
arr.shape

(2, 3)

In [16]:
arr.ndim

2

In [17]:
arr.dtype

dtype('int64')

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr = np.arange(9)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arr.shape

(9,)

In [22]:
arr.reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
arr.shape = (3, 3)

In [25]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
arr * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [27]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr > 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [29]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr + np.ones((3, 3))

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [32]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
arr[0]

array([0, 1, 2])

In [34]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
arr[0] = 1

In [36]:
arr

array([[1, 1, 1],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
numbers = [1, 2, 3, 4]

In [38]:
numbers[0]

1

In [39]:
numbers[:2]

[1, 2]

In [40]:
numbers

[1, 2, 3, 4]

In [41]:
arr

array([[1, 1, 1],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
arr[:2, 1:]

array([[1, 1],
       [4, 5]])

In [45]:
numbers = np.arange(9)

In [46]:
numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
numbers > 5

array([False, False, False, False, False, False,  True,  True,  True])

In [48]:
numbers[numbers > 5]

array([6, 7, 8])

In [49]:
arr

array([[1, 1, 1],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
arr[[0, 2]]

array([[1, 1, 1],
       [6, 7, 8]])

In [51]:
arr[[0, 2], 1:]

array([[1, 1],
       [7, 8]])

In [52]:
arr[[2, 0, 0, 0]]

array([[6, 7, 8],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [53]:
arr

array([[1, 1, 1],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
arr = np.arange(9).reshape((3, 3))

In [55]:
arr.mean()

4.0

In [56]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
arr.mean(axis=0)

array([3., 4., 5.])

In [58]:
# cond ? val1 if cond is true : val2 if cond is false

In [60]:
# val if cond else otherval;
b = 'yes' if 5 > 2 else 'no'

In [61]:
b

'yes'

In [62]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
np.where(arr > 5, 'YAAAAASSSS', 'NOOOOOOOPPPPEEE')

array([['NOOOOOOOPPPPEEE', 'NOOOOOOOPPPPEEE', 'NOOOOOOOPPPPEEE'],
       ['NOOOOOOOPPPPEEE', 'NOOOOOOOPPPPEEE', 'NOOOOOOOPPPPEEE'],
       ['YAAAAASSSS', 'YAAAAASSSS', 'YAAAAASSSS']], dtype='<U15')

In [64]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
arr.shape

(3, 3)