In [1]:
import numpy as np

In [2]:
print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
arr = np.arange(0, 3)

print(arr) # [0 1 2]
print(arr.dtype) # int64

float_arr = arr.astype('float64')

print(float_arr) # [0. 1. 2.] (floating point numbers, 64 bits)
print(float_arr.dtype) #

[0 1 2]
int64
[0. 1. 2.]
float64


In [4]:
data1 = np.array([[1, 2, 3], [4, 5, 6]])
data2 = np.array([[1, 1, 1], [10, 10, 10]])
print(data1 + data2)

[[ 2  3  4]
 [14 15 16]]


In [5]:
data = np.arange(1, 4)
print(data * 100)

[100 200 300]


In [6]:
data1 = np.array([[1, 2], [3, 4]])
data2 = np.array([[2, 2], [2, 2]])
data1 > data2

array([[False, False],
       [ True,  True]])

In [7]:
data = np.zeros(10)
sub = data[5:]
sub[0] = 99

In [8]:
data

array([ 0.,  0.,  0.,  0.,  0., 99.,  0.,  0.,  0.,  0.])

In [9]:
arr = np.array([1, 2, 3])
#twin_arr = arr.copy()
twin_arr = arr
twin_arr[0] = 99
print(arr, twin_arr)

[99  2  3] [99  2  3]


In [10]:
animals = np.array([['ant', 'bat', 'cat'], ['dog', 'elk', 'fox'], ['gnu', 'hen', 'ibis']])

In [11]:
animals

array([['ant', 'bat', 'cat'],
       ['dog', 'elk', 'fox'],
       ['gnu', 'hen', 'ibis']], dtype='<U4')

In [12]:
animals[2][1]

'hen'

In [13]:
animals[2, 1]

'hen'

In [14]:
nested = np.array([
    [[1, 2], [3, 4]], 
    [[5, 6], [7, 8]]])

In [15]:
nested

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
nested[0] = 480

In [17]:
nested

array([[[480, 480],
        [480, 480]],

       [[  5,   6],
        [  7,   8]]])

In [18]:
animals[:2, :2]

array([['ant', 'bat'],
       ['dog', 'elk']], dtype='<U4')

In [19]:
animals[1:2,1:]

array([['elk', 'fox']], dtype='<U4')

In [20]:
animals[:, 2:]

array([['cat'],
       ['fox'],
       ['ibis']], dtype='<U4')

In [21]:
words = np.array(['foo', 'bar', 'baz', 'qux', 'quxx', 'corge'])

In [22]:
words =='foo'

array([ True, False, False, False, False, False])

In [23]:
data = np.arange(32)

In [24]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [25]:
data.merge?

Object `data.merge` not found.


In [32]:
nested = np.array([
    [[1, 2], 
     [3, 4]], 

    [[5, 6], 
     [7, 8]]])

In [33]:
nested

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
nested[0:1] = 480

In [35]:
nested

array([[[480, 480],
        [480, 480]],

       [[  5,   6],
        [  7,   8]]])

In [36]:
data = np.arange(6)
data_slice = data[2:4]
data_slice[:] = 8

In [37]:
data

array([0, 1, 8, 8, 4, 5])

In [50]:
import numpy as np
data = np.ones((5,3))
for i in range(5):
    data[i]=i

In [51]:
data

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [52]:
# data[data < 2] = 99

In [53]:
data

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [54]:
data[:2] = 222

In [55]:
data

array([[222., 222., 222.],
       [222., 222., 222.],
       [  2.,   2.,   2.],
       [  3.,   3.,   3.],
       [  4.,   4.,   4.]])